// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdWdshWfsVOVguD2SE0eXPlGYWUqFo7kI',
    appId: '1:666868437388:web:3927efb0f3a7b1e9f7c6a9',
    messagingSenderId: '666868437388',
    projectId: 'car-rental-app-32c18',
    authDomain: 'car-rental-app-32c18.firebaseapp.com',
    storageBucket: 'car-rental-app-32c18.firebasestorage.app',
    measurementId: 'G-68TMX0XL4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0CXHrIsWSTWOn2vEh2rBrlbbZKU3adH0',
    appId: '1:666868437388:android:35fd72425a8194bef7c6a9',
    messagingSenderId: '666868437388',
    projectId: 'car-rental-app-32c18',
    storageBucket: 'car-rental-app-32c18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrCuCKPn7MI5tiG1fGMZIhounDKPfj_tg',
    appId: '1:666868437388:ios:63aa4e1c775df586f7c6a9',
    messagingSenderId: '666868437388',
    projectId: 'car-rental-app-32c18',
    storageBucket: 'car-rental-app-32c18.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrCuCKPn7MI5tiG1fGMZIhounDKPfj_tg',
    appId: '1:666868437388:ios:63aa4e1c775df586f7c6a9',
    messagingSenderId: '666868437388',
    projectId: 'car-rental-app-32c18',
    storageBucket: 'car-rental-app-32c18.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdWdshWfsVOVguD2SE0eXPlGYWUqFo7kI',
    appId: '1:666868437388:web:8301cda6ba0b0d11f7c6a9',
    messagingSenderId: '666868437388',
    projectId: 'car-rental-app-32c18',
    authDomain: 'car-rental-app-32c18.firebaseapp.com',
    storageBucket: 'car-rental-app-32c18.firebasestorage.app',
    measurementId: 'G-58C27CTCEH',
  );
}
